### ISSUE TITLE
Toggle window focus hotkey does not work when switching the window manually

### ISSUE THREAD

**Issue by RYSKZ** [dragonwocky/obsidian-tray#30] opened 2023-09-04 03:21 UTC
Hello,
I have encountered an issue related to the toggle window focus hotkey feature. It seems that this functionality fails to operate when the Obsidian window is manually switched, either by clicking on another program's taskbar icon or using the Alt+Tab or Alt+Esc key combinations. However, once I manually click on the Obsidian taskbar icon to restore the window, the toggle window focus hotkey functionality works properly again.

It is not a big issue but is a bit annoying because I am used to Alt+Tabbing to switch windows and whenever I do so the hotkey stops working, and I have to resort to clicking the Obsidian icon to restore its functionality.

The steps to reproduce are the following:
1. Open the Obsidian application.
2. Make sure that there are several applications or windows running next to Obsidian.
3. Make sure the hotkey to toggle window focus is working as intended. I currently have it set to Alt+Q, but I have also reproduced this problem successfully with the default hotkey Ctrl + Shift + Tab.
4. Activate the Obsidian window.
5. Use the keyboard shortcuts Alt+Tab or Alt+Esc to switch to another open application.
6. Attempt to use the hotkey to change the focus of the window and verify that the Obsidian window is not restored.

Also, I wanted to thank you for all your work, this plugin is really coming in handy.

**Comment by Azona77** [comment] 2023-09-04 09:26
Same issue. 
I returned to 0.3.3 and it functions good. Hope this may pinpoint where the isuue is.

**Comment by dragonwocky** [comment] 2023-09-04 11:29
Dup of https://github.com/dragonwocky/obsidian-tray/issues/29, but I appreciate the extra information - I wasn't able to figure out the cause from the original bug report. I've done some more debugging following these steps and it looks like this is related to the maximised window preservation that was added in 0.3.4 (it only occurs if the window is maximised and then alt-tabbed).

This should be fixed in 0.3.5 (just released).

**Closed by dragonwocky** 2023-09-04 11:29 UTC

**Comment by RYSKZ** [comment] 2023-09-04 21:31
My apologies for the duplication. I reviewed the open issues, including the one you mention, but mistakenly thought it reported a related but different problem.
I figured it was due to the maximized window. Thank you very much for resolving this problem. It works perfectly now.
